### ISSUE TITLE
requires xmlrpc module

### ISSUE THREAD

**Issue by kylewm** [indieweb/mention-client-php#22]
The [call to xmlrpc_decode](https://github.com/indieweb/mention-client-php/blob/master/src/IndieWeb/MentionClient.php#L75) failed on vanilla Ubuntu because I did not have the `php5-xmlrpc` module installed (Debian-derived distros at least seem to break less common stdlib functions into separate modules)

I think it would be worthwhile to make this a soft requirement (check for existence of the function before calling it) or remove it altogether and verify the response manually, since pingback is kind of secondary and we're not doing much with the response anyway.

**Comment by kylewm** [comment]
Actually could we just return true if the response code is 200, 201, 202, just like webmentions?

**Comment by aaronpk** [comment]
hm, not sure how I ended up adding `xmlrpc_decode` in there, since the whole reason I wrote my own encode method was to avoid relying on that function existing. 

I don't actually see anything in the [Pingback spec](http://www.hixie.ch/specs/pingback/pingback#TOC3) about HTTP codes. Does this mean that current Pingback implementations might return HTTP 200 even if there is an error?

I would be okay with regexing the XML response to check for an error though. (I know I know, but come on, it's better than XMLRPC)

**Comment by voxpelli** [comment]
```php
return $response['body'] && strpos($response['body'], '<fault>') === false && strpos($response['body'], '<string>') !== false;
```

As long as people haven't added lots of whitespace and attributes to an XML-RPC response then I think that would do the trick after having read the wikipedia page for XML-RPC quickly.

**Comment by aaronpk** [comment]
Could also remove newlines and whitespace before testing just to be safe? Otherwise this looks fine.
